#!/bin/sh
set -e
mkdir -p /var/lib/ringtones
chown mobile:mobile /var/lib/ringtones
chmod 0755 /var/lib/ringtones
mkdir -p /var/jb/var/mobile/Library/Importone/IPC
chown -R mobile:mobile /var/jb/var/mobile/Library/Importone
chmod 0700 /var/jb/var/mobile/Library/Importone/IPC
launchctl bootout system /var/jb/Library/LaunchDaemons/com.sonicedc.importoned.plist 2>/dev/null || true
launchctl bootstrap system /var/jb/Library/LaunchDaemons/com.sonicedc.importoned.plist
exit 0
